package tencentcloud

const (
	DDOS_DESCRIBE_LIMIT = 50
)

const (
	DDOS_BLACK_TYPE = "black"
	DDOS_WHITE_TYPE = "white"
)

const (
	DDOS_PORT_ACTION_DROP     = "drop"
	DDOS_PORT_ACTION_TRANSMIT = "transmit"
	DDOS_PORT_ACTION_FORWARD  = "forward"
)

var DDOS_PORT_ACTION = []string{DDOS_PORT_ACTION_DROP, DDOS_PORT_ACTION_TRANSMIT, DDOS_PORT_ACTION_FORWARD}

const (
	DDOS_PACKET_ACTION_DROP             = "drop"
	DDOS_PACKET_ACTION_TRANSMIT         = "transmit"
	DDOS_PACKET_PROTOCOL_DROP_BLACK     = "drop_black"
	DDOS_PACKET_PROTOCOL_DROP_RST       = "drop_rst"
	DDOS_PACKET_PROTOCOL_DROP_BLACK_RST = "drop_black_rst"
	DDOS_PACKET_PROTOCOL_FORWARD        = "forward"
)

var DDOS_PACKET_ACTION = []string{DDOS_PACKET_ACTION_DROP, DDOS_PACKET_ACTION_TRANSMIT, DDOS_PACKET_PROTOCOL_DROP_BLACK, DDOS_PACKET_PROTOCOL_DROP_RST, DDOS_PACKET_PROTOCOL_DROP_BLACK_RST, DDOS_PACKET_PROTOCOL_FORWARD}

const (
	DDOS_MATCH_TYPE_SUNDAY = "sunday"
	DDOS_MATCH_TYPE_PCRE   = "pcre"
)

var DDOS_MATCH_TYPE = []string{DDOS_MATCH_TYPE_SUNDAY, DDOS_MATCH_TYPE_PCRE}

const (
	DDOS_MATCH_SWITCH_ON_L3 = "begin_l3"
	DDOS_MATCH_SWITCH_ON_L4 = "begin_l4"
	DDOS_MATCH_SWITCH_ON_L5 = "begin_l5"
	DDOS_MATCH_SWITCH_OFF   = "no_match"
)

var DDOS_MATCH_SWITCH = []string{DDOS_MATCH_SWITCH_ON_L3, DDOS_MATCH_SWITCH_ON_L4, DDOS_MATCH_SWITCH_ON_L4, DDOS_MATCH_SWITCH_ON_L5, DDOS_MATCH_SWITCH_OFF}

const (
	DDOS_PROTOCOL_TCP  = "tcp"
	DDOS_PROTOCOL_UDP  = "udp"
	DDOS_PROTOCOL_ICMP = "icmp"
	DDOS_PROTOCOL_ALL  = "all"
)

var DDOS_PROTOCOL = []string{DDOS_PROTOCOL_TCP, DDOS_PROTOCOL_UDP, DDOS_PROTOCOL_ICMP, DDOS_PROTOCOL_ALL}

const (
	DDOS_AI_SWITCH_ON  = "on"
	DDOS_AI_SWITCH_OFF = "off"
)

var DDOS_AI_SWITCH = []string{DDOS_AI_SWITCH_ON, DDOS_AI_SWITCH_OFF}

func bool2int64(v bool) int64 {
	result := int64(0)
	if v {
		result = 1
	}
	return result
}
